### ISSUE TITLE
Pushing contents failed when email is still unverified

### ISSUE THREAD

**Issue by k0ms** [joathamneil/TAC#3]
Paps tinry ko i-pull ung repository pero wala ung <<< ### na mga codes ibig sabihin asa local mo lang ung may merge conflict. Eto steps para maayos tska ma refresh ung repository mo

Execute following commands tska merge 
1. cd myApp
2. cd ../
3. git clone https://github.com/joathamneil/TAC.git
4. Merged mo ung modified codes mo sa myApp folder dun sa TAC folder. After matapos nung step 3 magkakaroon ng TAC folder.
   4.1 Ung layout.jade minimize lang to codes na para sa lahat ng iba pang jade files. Ung index.jade andun na nakalagay ung div for pictures.
5.  git add .
6. git commit -m "Insert you rmessage"
7. git push origin master
8. go back to myApp folder (cd myApp)
9. git remote -v
10. copy the heroku url 
11. go back to TAC folder (cd TAC)
12. git remote add heroku <paste url here>
13. git push heroku master

Hehehe reply ka lang dito kapag meron issue

**Comment by joathamneil** [comment]
pati ung naka up sa heroku ganun na din ang error
hahaha

On Mon, Mar 30, 2015 at 7:33 AM, k0ms notifications@github.com wrote:

> Paps tinry ko i-pull ung repository pero wala ung <<< ### na mga codes
> ibig sabihin asa local mo lang ung may merge conflict. Eto steps para
> maayos tska ma refresh ung repository mo
> 
> Execute following commands tska merge
> 1. cd myApp
> 2. cd ../
> 3. git clone https://github.com/joathamneil/TAC.git
> 4. Merged mo ung modified codes mo sa myApp folder dun sa TAC folder.
>    After matapos nung step 3 magkakaroon ng TAC folder. 4.1 Ung layout.jade
>    minimize lang to codes na para sa lahat ng iba pang jade files. Ung
>    index.jade andun na nakalagay ung div for pictures.
> 5. git add .
> 6. git commit -m "Insert you rmessage"
> 7. git push origin master
> 8. git push heroku master
> 
> Hehehe reply ka lang dito kapag meron issue
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/joathamneil/TAC/issues/3.

## 

Joatham Neil I. Lagrimas
Mobile: +63 9178266345

**Comment by k0ms** [comment]
hahaha weird hindi dapat siya pumasok ng heroku since the commit failed. bakit kaya, I think bug siya sa github or heroku. I'll try to recreate the issue if I have time.  Na execute mo na ung nasa taas? Once na okay na ung issue pwede mo na I click ung close and comment.

**Comment by k0ms** [comment]
Repository is now on its latest commit and working state
